"""能力解析端口；未来实现必须验证固定版本、授权与能力存在性。"""

from typing import Protocol

from evoteam.domain.common import AssetRef
from evoteam.domain.role import RoleDefinition, RoleType


class CapabilityRegistry(Protocol):
    def get_role(self, role: RoleType) -> RoleDefinition: ...
    def get_prompt(self, ref: AssetRef) -> str: ...
    def require_skill(self, ref: AssetRef) -> None: ...
    def require_tool(self, ref: AssetRef) -> None: ...
    def require_model(self, ref: AssetRef) -> None: ...
